### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by robmroi03** [strifel/githubYearCommits#1]
- You see when a user last committed something. 
- Percentage better displayed (in Table)
- webhook integration when a user commits (e.g. Discord):
`Update commits;`
`If (user.Commits > user.OldCommits){`
`Webhook.notify;`
`}`

**Comment by robmroi03** [comment]
- Select the year (like 2015)

**Comment by strifel** [comment]
- Change Location of Database centrally

**Comment by strifel** [comment]
A lot of these things are not relevant anymore or already done.

If there is still a need for something please open a seperate issue.
